<?php $callback_url_ed = base_url()."checkout/update"; ?>
<div class="container">
  <div class="row">
    <div class="span6">
      <h4 class="lead"><small>this is a secure platform and you can make advance payment at this point </small></h4>
     <?php
include_once('OAuth.php');
//pesapal params
$token = $params = NULL;
/*
PesaPal Sandbox is at http://demo.pesapal.com. Use this to test your developement and 
when you are ready to go live change to https://www.pesapal.com.
*/
$consumer_key = 'S6SilOFxP4mU5WVoM7o6zqASte05bT9l';//Register a merchant account on
                   //demo.pesapal.com and use the merchant key for testing.
                   //When you are ready to go live make sure you change the key to the live account
                   //registered on www.pesapal.com!
$consumer_secret = '4uqUNOkZRcfGVwiFzVX7Tj/hVKU=';// Use the secret from your test
                   //account on demo.pesapal.com. When you are ready to go live make sure you 
                   //change the secret to the live account registered on www.pesapal.com!
$signature_method = new OAuthSignatureMethod_HMAC_SHA1();
$iframelink = 'http://demo.pesapal.com/api/PostPesapalDirectOrderV4';//change to      
                   //https://www.pesapal.com/API/PostPesapalDirectOrderV4 when you are ready to go live!

//get form details
$amount = $_POST['amount'];
$amount = number_format($amount, 2);//format amount to 2 decimal places

$desc = $_POST['description'];
$type = $_POST['type']; //default value = MERCHANT
$reference = $_POST['reference'];//unique order id of the transaction, generated by merchant
$first_name = $_POST['first_name'];
$last_name = $_POST['last_name'];
$email = $_POST['email'];
$phonenumber = '123548752';//ONE of email or phonenumber is required

$callback_url =$callback_url_ed;  //redirect url, the page that will handle the response from pesapal.

$post_xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><PesapalDirectOrderInfo xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Amount=\"".$amount."\" Description=\"".$desc."\" Type=\"".$type."\" Reference=\"".$reference."\" FirstName=\"".$first_name."\" LastName=\"".$last_name."\" Email=\"".$email."\" PhoneNumber=\"".$phonenumber."\" xmlns=\"http://www.pesapal.com\" />";
$post_xml = htmlentities($post_xml);

$consumer = new OAuthConsumer($consumer_key, $consumer_secret);

//post transaction to pesapal
$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET", $iframelink, $params);
$iframe_src->set_parameter("oauth_callback", $callback_url);
$iframe_src->set_parameter("pesapal_request_data", $post_xml);
$iframe_src->sign_request($signature_method, $consumer, $token);

//display pesapal - iframe and pass iframe_src
?>
<iframe src="<?php echo $iframe_src;?>" width="100%" height="700px"  scrolling="no" frameBorder="0">
	<p>Browser unable to load iFrame</p>
</iframe> 

       </div>
    <div class="span6 ">
      <div class="address">
            <h4 class="lead"><small>Your details of payment are has below  </small></h4>
      <div class="well">

    
         <?php if(isset($records)): foreach($records as $row):?>
         
<table class="small">
	<thead>
	<tr>
		<th>Name</th>
		<th>Email</th>
		<th>Phone</th>
        <th>Platform</th>
		<th>Bussines type</th>
		<th>Budget</th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
        <td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td><?php echo $row->name .'  '. $row->lastName ?></td>
		<td><?php echo $row->email ?></td>
		<td><?php echo $row->phone ?></td>
        <td><?php // echo $row->platform ?></td>
		<td><?php echo $row->bussinesType ?></td>
		<td><?php echo $row->budget ?></td>
	</tr>
	</tbody>
 <table width="100%" border="0" cellspacing="0" cellpadding="0">
 <thead>
  <tr>
    <th>Project Description</th>
  </tr>
  </thead>
  <tbody
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><?php echo $row->projectdetail ?></td>
  </tr>
  </tbody>
</table>

</table>

	  <?php endforeach;?>
      
      <?php else:?>
      <h2>no records were found</h2>
      
      <?php endif;?>
</div> <!--well-->
      </div>
    </div>
  </div>
</div>
